version: "3.9"

services:
  db:
    container_name: db
    image: "mysql:8.3"
    env_file:
      - ./db/.env
    ports:
      - 3306:3306
    restart: always
    volumes:
      - db-storage:/var/lib/mysql
  backend:
    container_name: backend
    build: .
    volumes:
      - type: bind
        source: ./backend
        target: /backend
    ports:
      - 8080:8080
    env_file:
      - ./backend/.env
    depends_on:
      - db
volumes:
  db-storage:
